# Baichuan Scheduler Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bc-scheduler-rlength-account
  namespace: inference-service-test
---
# Baichuan Scheduler Role: minimal permissions.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bc-scheduler-rlength-role
  namespace: inference-service-test
rules:
- apiGroups: [""]
  resources:  ["endpoints"]
  verbs: ["get", "watch", "list"]
---
# Baichuan Scheduler RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bc-scheduler-rlength-rolebinding
  namespace: inference-service-test
subjects:
- kind: ServiceAccount
  name: bc-scheduler-rlength-account
  namespace: inference-service-test
roleRef:
  kind: Role
  name: bc-scheduler-rlength-role
  apiGroup: rbac.authorization.k8s.io
---
# Baichuan Scheduler Deployment.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc-scheduler-rlength
  labels:
    app: bc-scheduler-rlength
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bc-scheduler-rlength
  template:
    metadata:
      labels:
        app: bc-scheduler-rlength
    spec:
      serviceAccountName: bc-scheduler-rlength-account
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - bc-scheduler-rlength
                topologyKey: kubernetes.io/hostname
      imagePullSecrets:
          - name: baichuan-inference-service
      terminationGracePeriodSeconds: 120
      containers:
      - name: bc-scheduler-rlength
        image: harbor.ppio.baichuan-ai.com/inferenceservice/baichuan-infer:bcscheduler-retry-v1.1.0
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "1Gi"
            cpu: "1"
        imagePullPolicy: IfNotPresent
        command: ["./bcScheduler"]
        args: 
          - "--load-balancer-port=8890"
          - "--retriable-status-codes=500,502,503,504,424,422"
        lifecycle:
          preStop:
            exec:
              command:
              - sleep
              - "0" # for testing
        ports:
        - containerPort: 8890
        livenessProbe:
          httpGet:
            path: /health
            port: 8890
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /health
            port: 8890
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 1
---
# Baichuan Scheduler Service.
apiVersion: v1
kind: Service
metadata:
  name: bc-scheduler-rlength
  labels:
    app: bc-scheduler-rlength
spec:
  selector:
    app: bc-scheduler-rlength
  ports:
  - protocol: TCP
    port: 8890
    targetPort: 8890
  type: ClusterIP
---
# Baichuan Scheduler Ingress.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bc-scheduler-rlength
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10" # in seconds
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"   # in seconds
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"   # in seconds
    nginx.ingress.kubernetes.io/limit-rps: "10000"  # max request per second
    nginx.ingress.kubernetes.io/limit-connections: "1000"  # max connections
spec:
  ingressClassName: nginx
  rules:
  - host: chat-bc-scheduler-rlength.test.ppio.bc-inner.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: bc-scheduler-rlength
            port:
              number: 8890
  - host: chat-bc-scheduler-rlength.test.inference.proxy.bc-inner.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: bc-scheduler-rlength
            port:
              number: 8890
